# Generated by Django 2.1.7 on 2019-03-18 20:09

import alumni.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumni', '0015_auto_20190318_2009'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.CreateModel(
                    name='PaymentInformation',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tier', alumni.fields.TierField(help_text='Membership Tier')),
                        ('payment_type', alumni.fields.PaymentTypeField(choices=[('card', 'Credit or Debit Card'), ('sepa', 'Automatic Bank Transfer (SEPA)')], default='card', max_length=4)),
                        ('starterReason', models.TextField(blank=True, null=True)),
                        ('token', models.CharField(blank=True, help_text='The stripe card token for the user', max_length=255, null=True)),
                        ('customer', models.CharField(blank=True, help_text='The stripe customer id for the user', max_length=255, null=True)),
                        ('subscription', models.CharField(blank=True, help_text='The payment token for the customer', max_length=255, null=True)),
                        ('sepa_mandate', jsonfield.fields.JSONField(blank=True, null=True)),
                        ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='alumni.Alumni')),
                    ],
                ),
            ],
        )
    ]
