# Generated by Django 2.1.7 on 2019-03-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0016_setupcompleted'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentInformation',
            new_name='MembershipInformation',
        ),
    ]
