# Generated by Django 2.1.7 on 2019-03-31 10:08

import alumni.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields

def map_to_subscription(apps, schema_editor):
    MembershipInformation = apps.get_model('payments', 'MembershipInformation')
    SubscriptionInformation = apps.get_model('payments', 'SubscriptionInformation')

    # Iterate over all alumni
    for mi in MembershipInformation.objects.all():
        instance = SubscriptionInformation.objects.create(
            member=mi.member,
            start=mi.member.setup.date,
            end=None,
            subscription=mi.subscription,
            tier=mi.tier
        )
        


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0016_setupcompleted'),
        ('payments', '0002_auto_20190331_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='The start date for the subscription')),
                ('end', models.DateTimeField(blank=True, help_text='The end date for the subscription', null=True)),
                ('subscription', models.CharField(blank=True, help_text='The Stripe Subscription ID for the given subscription', max_length=255, null=True)),
                ('tier', alumni.fields.TierField(help_text='Membership Tier')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
            ],
        ),
        migrations.RunPython(map_to_subscription),
        migrations.RemoveField(
            model_name='membershipinformation',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='membershipinformation',
            name='sepa_mandate',
        ),
        migrations.RemoveField(
            model_name='membershipinformation',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='membershipinformation',
            name='token',
        ),
    ]
