# Generated by Django 2.1.7 on 2019-04-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190331_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipinformation',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='alumni.Alumni'),
        ),
    ]
