# Generated by Django 2.1.11 on 2019-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190401_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninformation',
            name='external',
            field=models.BooleanField(default=False, help_text='Subscription is managed externally'),
        ),
    ]
