# Generated by Django 2.2.9 on 2020-01-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_subscriptioninformation_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipinformation',
            name='starterReason',
        ),
    ]
