# Generated by Django 2.2.10 on 2020-02-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_membershipinformation_starterreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipinformation',
            name='stripe_check',
            field=models.BooleanField(blank=True, help_text='Internal Column used by Stripe checking', null=True),
        ),
    ]
