# Generated by Django 2.2.10 on 2020-02-22 11:07

import alumni.fields.tier
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_membershipinformation_stripe_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipinformation',
            name='desired_tier',
            field=alumni.fields.tier.TierField(blank=True, help_text='Desired Membership Tier', null=True),
        ),
    ]
