# Generated by Django 2.2.13 on 2020-08-24 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0020_auto_20200412_1210'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Enable showing this vote link')),
                ('title', models.TextField(help_text='Title of this link')),
                ('description', models.TextField(help_text='Description of this link')),
                ('url', models.URLField(help_text='URL where the vote takes place')),
            ],
        ),
        migrations.CreateModel(
            name='VoteToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('alumni', models.ForeignKey(help_text='Alumni this token is for', on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
                ('vote', models.ForeignKey(help_text='Vote this Token is associated to', on_delete=django.db.models.deletion.CASCADE, to='registry.VoteLink')),
            ],
            options={
                'ordering': ('token',),
                'unique_together': {('vote', 'alumni')},
            },
        ),
    ]
