# Generated by Django 2.2.13 on 2020-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_votelink_votetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votelink',
            name='url',
            field=models.URLField(help_text='URL where the vote takes place. Use ${token} as a placeholder for the token. '),
        ),
    ]
