# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(default=False)),
                ('set_social', models.BooleanField(default=False)),
                ('set_jacobs', models.BooleanField(default=False)),
                ('set_address', models.BooleanField(default=False)),
                ('set_job', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='alumni.Alumni')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='alumni.Alumni'),
        ),
        migrations.AlterField(
            model_name='jacobsdata',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jacobs', to='alumni.Alumni'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='alumni.Alumni'),
        ),
    ]
