# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 11:58
from __future__ import unicode_literals

import alumni.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumni_createmissingapprovals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=alumni.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='nationality',
            field=alumni.fields.CountryField(help_text='You can select multiple options by holding the <em>Ctrl</em> key (or <em>Command</em> on Mac) while clicking', max_length=746, multiple=True),
        ),
    ]
