# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 09:56
from __future__ import unicode_literals

import alumni.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_paymentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='birthday',
            field=models.DateField(help_text='Your birthday'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='middleName',
            field=models.CharField(blank=True, help_text='Your middle name(s)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='tier',
            field=alumni.fields.TierField(choices=[('st', 'Starter (1€ per year)'), ('co', 'Contributor (49€ per year)'), ('pa', 'Patron (249€ per year)')], default='st', help_text='Membership Tier', max_length=2),
        ),
    ]
