# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-31 15:23
from __future__ import unicode_literals

import alumni.fields
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_paymentinformation_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='sepa_mandate',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_type',
            field=alumni.fields.PaymentTypeField(choices=[('card', 'Credit or Debit Card'), ('sepa', 'SEPA bank transfer')], default='card', max_length=4),
        ),
    ]
