# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20171202_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='gsuite',
            field=models.EmailField(blank=True, help_text='The G-Suite E-Mail of the user', max_length=254, null=True),
        ),
    ]
