# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20180331_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='starterReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
