# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_approval_gsuite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='customer',
            field=models.CharField(blank=True, help_text='The stripe customer id for the user', max_length=255, null=True),
        ),
    ]
