# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 22:38
from __future__ import unicode_literals

import alumni.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_auto_20190115_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', alumni.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together=set([('country', 'zip')]),
        ),
    ]
