# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_auto_20190202_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='showOnMap',
            field=models.BooleanField(default=False, help_text='Show my social media contact information on the alumni map. '),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressVisible',
            field=models.BooleanField(default=False, help_text='Include me on the alumni map. By selecting this checkbox, your location (approximated by your zip code), your city, and other information about you will be visible on the map interface to other users that have chosen to be visible as well. '),
        ),
    ]
