# Generated by Django 2.1.7 on 2019-03-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_auto_20190218_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressVisible',
            field=models.BooleanField(blank=True, default=False, help_text='Include me on Alumni Map & Search. By selecting this checkbox, your location (approximated by your zip code), your city, and other information about you will be visible on the map & search interface to other users that have chosen to be visible as well. '),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='birthdayVisible',
            field=models.BooleanField(blank=True, default=False, help_text='Make birthday visible to others'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='resetExistingEmailPassword',
            field=models.BooleanField(blank=True, default=False, help_text='Reset password to existing email address'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval',
            field=models.BooleanField(blank=True, default=False, help_text='Has the user been approved by an admin?'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='alumniMentor',
            field=models.BooleanField(blank=True, default=False, help_text='I would like to sign up as an alumni mentor'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='showOnMap',
            field=models.BooleanField(blank=True, default=False, help_text='Show my social media & contact information (like @jacobs-alumni email) on the alumni map. '),
        ),
    ]
