# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_auto_20171203_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressVisible',
            field=models.BooleanField(default=False, help_text='Include me on the alumni map (only your city will be visible to others)'),
        ),
    ]
