# Generated by Django 2.1.7 on 2019-03-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_auto_20190309_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoLocation',
        ),
    ]
