# Generated by Django 2.1.7 on 2019-03-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_delete_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(blank=True, help_text='Secret Search Text that the member can be found with', null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atlas', to='alumni.Alumni')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='addressVisible',
            field=models.BooleanField(blank=True, default=False, help_text='Include me in the Alumni Atlas. By selecting this checkbox, your location (approximated by your zip code), your city, and other information about you will be visible on the map & search interface to other users that have chosen to be visible as well. '),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='showOnMap',
            field=models.BooleanField(blank=True, default=False, help_text='Show my social media & contact information (like @jacobs-alumni email) on the alumni atlas. '),
        ),
    ]
