# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='starterReason',
            field=models.TextField(blank=True, help_text='Please provide a short explanation below on why you choose the starter plan. ', null=True),
        ),
    ]
