# Generated by Django 2.1.7 on 2019-03-09 16:52

from django.db import migrations, models
from django.core.exceptions import ObjectDoesNotExist

def map_to_atlas(apps, schema_editor):
    Alumni = apps.get_model('alumni', 'alumni')
    AtlasSettings = apps.get_model('alumni', 'atlassettings')

    # Iterate over all alumni
    for a in Alumni.objects.all():
        # extract the previous settings
        try:
            included = a.address.addressVisible
            birthdayVisible = a.birthdayVisible
            contactInfoVisible = a.social.showOnMap
        except ObjectDoesNotExist:
            continue

        # store them in a new settings
        setting, created = AtlasSettings.objects.get_or_create(member=a)
        setting.included = included
        setting.birthdayVisible = birthdayVisible
        setting.contactInfoVisible = contactInfoVisible
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_auto_20190309_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlassettings',
            name='birthdayVisible',
            field=models.BooleanField(blank=True, default=False, help_text='Show Birthday on my Alumni Atlas Profile'),
        ),
        migrations.AddField(
            model_name='atlassettings',
            name='contactInfoVisible',
            field=models.BooleanField(blank=True, default=False, help_text='Show Social Media and Contact information (like @jacobs-alumni email) on the Alumni Atlas Profile Page. '),
        ),
        migrations.AddField(
            model_name='atlassettings',
            name='included',
            field=models.BooleanField(blank=True, default=False, help_text='Include me in the Alumni Atlas. By selecting this checkbox, your location (approximated by your zip code), your city, and other information about you will be visible on the atlas interface to other users. '),
        ),
        migrations.RunPython(map_to_atlas),
        migrations.RemoveField(
            model_name='address',
            name='addressVisible',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='birthdayVisible',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='showOnMap',
        ),
    ]
