# Generated by Django 2.1.7 on 2019-03-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_auto_20190309_1652'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable('atlassettings', 'atlas_atlassettings'),
            ],
            state_operations=[    
                migrations.DeleteModel(
                    name='AtlasSettings',
                ),
            ],
        ),
    ]
