# Generated by Django 2.1.7 on 2019-03-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_auto_20190310_1245'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable('paymentinformation', 'payments_paymentinformation'),
            ],
            state_operations=[    
                migrations.DeleteModel(
                    name='PaymentInformation',
                ),
            ],
        ),
    ]
