# Generated by Django 2.1.7 on 2019-06-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0016_setupcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='time',
            field=models.DateTimeField(blank=True, help_text='Time the user has been approved', null=True),
        ),
    ]
