# Generated by Django 2.2.9 on 2020-02-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0017_approval_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='lastName',
            new_name='familyName',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='firstName',
            new_name='givenName',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='familyName',
            field=models.CharField(help_text='Your family name', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='givenName',
            field=models.CharField(help_text='Your given name', max_length=255),
        ),
    ]
