# Generated by Django 2.2.11 on 2020-04-12 12:10

import alumni.fields.country
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0019_auto_20200322_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='E.g. Campus Ring 1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='E.g. Bremen', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=alumni.fields.country.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, help_text='E.g. 28759', max_length=255, null=True),
        ),
    ]
