# Generated by Django 2.1.7 on 2019-03-09 15:22

import alumni.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', alumni.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together={('country', 'zip')},
        ),
    ]
