# Generated by Django 2.1.7 on 2019-03-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_auto_20190310_1245'),
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.CreateModel(
                    name='AtlasSettings',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('included', models.BooleanField(blank=True, default=False, help_text='Include me in the Alumni Atlas. By selecting this checkbox, your location (approximated by your zip code), your city, and other information about you will be visible on the atlas interface to other users. ')),
                        ('birthdayVisible', models.BooleanField(blank=True, default=False, help_text='Show Birthday on my Alumni Atlas Profile')),
                        ('contactInfoVisible', models.BooleanField(blank=True, default=False, help_text='Show Social Media and Contact information (like @jacobs-alumni email) on the Alumni Atlas Profile Page. ')),
                        ('secret', models.TextField(blank=True, help_text='Secret Search Text that the member can be found with', null=True)),
                        ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atlas', to='alumni.Alumni')),
                    ],
                ),
            ],
        )
    ]
