# Generated by Django 3.1.14 on 2022-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_atlassettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='group1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='group2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='group3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
