# Generated by Django 2.2.13 on 2020-11-02 20:20

from django.db import migrations, models
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('payment_stream', models.CharField(choices=[('stripe', 'Stripe'), ('bank', 'Bank Account'), ('other', 'Other')], max_length=32)),
                ('payment_reference', models.CharField(help_text='The unique reference to this payment. For bank accounts, use the SEPA transfer ID. For other payment sources, leave a short note.', max_length=256)),
                ('received_on', models.DateField(help_text='The day this donation was received.')),
                ('issued_on', models.DateField(help_text='The day this receipt was issued.')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=4, default_currency='EUR', max_digits=14)),
                ('recipent_text', models.TextField(help_text='The full name and postal address of the donation recipient, on multiple lines of text.')),
                ('receipt_pdf', models.FileField(editable=False, upload_to='')),
            ],
        ),
    ]
