# Generated by Django 2.2.13 on 2020-11-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_receipts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationreceipt',
            old_name='recipent_text',
            new_name='recipient_info',
        ),
    ]
