# Generated by Django 2.2.13 on 2020-11-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_receipts', '0002_auto_20201102_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreceipt',
            name='receipt_pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
