# Generated by Django 2.2.13 on 2020-11-03 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation_receipts', '0003_auto_20201102_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationreceipt',
            old_name='recipient_info',
            new_name='sender_info',
        ),
        migrations.AddField(
            model_name='donationreceipt',
            name='received_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationreceipt',
            name='receipt_pdf',
            field=models.FileField(editable=False, upload_to=''),
        ),
    ]
