# Generated by Django 2.2.13 on 2020-11-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_receipts', '0004_auto_20201103_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreceipt',
            name='sender_info',
            field=models.TextField(help_text='The full name and postal address of the donation sender, on multiple lines of text.'),
        ),
    ]
