# Generated by Django 2.2.13 on 2020-11-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_receipts', '0005_auto_20201103_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationreceipt',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
