# Generated by Django 2.2.13 on 2020-11-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_receipts', '0007_donationreceipt_internal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreceipt',
            name='issued_on',
            field=models.DateField(auto_now=True, help_text='The day this receipt was issued.'),
        ),
    ]
