# Generated by Django 3.1 on 2020-11-18 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation_receipts', '0008_auto_20201110_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationreceipt',
            name='email_name',
            field=models.CharField(default='', help_text='How to adress the person donating, as in "Dear <email_name>"', max_length=64),
        ),
        migrations.AddField(
            model_name='donationreceipt',
            name='email_sent',
            field=models.BooleanField(default=False, editable=False, help_text='If this is ticked, an email has been sent.'),
        ),
        migrations.AddField(
            model_name='donationreceipt',
            name='email_to',
            field=models.EmailField(default='', help_text='The email address to send the receipt to.', max_length=254),
        ),
        migrations.AlterField(
            model_name='donationreceipt',
            name='finalized',
            field=models.BooleanField(default=False, help_text='Once finalized, the receipt details will no longer be editable.'),
        ),
        migrations.AlterField(
            model_name='donationreceipt',
            name='received_from',
            field=models.ForeignKey(blank=True, help_text='The user that this donation receipt should be sent to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
