# Generated by Django 3.1 on 2020-11-29 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation_receipts', '0009_auto_20201118_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationreceipt',
            name='email_name',
            field=models.CharField(default='', help_text='How to adress the person donating, as in "Dear email name"', max_length=64),
        ),
        migrations.AlterField(
            model_name='donationreceipt',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='If this is ticked, an email has been sent.'),
        ),
        migrations.AlterField(
            model_name='donationreceipt',
            name='received_from',
            field=models.ForeignKey(blank=True, help_text='The user that this donation receipt should be shown to in the portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
