# Generated by Django 3.1.14 on 2022-08-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20220818_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='checkout_session_id',
            new_name='payment_id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
