# Generated by Django 3.1.14 on 2022-09-06 20:36

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20220820_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10),
        ),
    ]
