# Generated by Django 3.1.14 on 2022-09-08 13:43

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20220907_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_choices=(('EUR', 'Euros'), ('USD', 'US Dollars')), decimal_places=2, default_currency='EUR', help_text='Use "." as the decimal separator, i.e. "1000.23" means 1000 Euros and 23 Cents. ', max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars')], default='EUR', editable=False, max_length=3),
        ),
    ]
