"""
Django settings for MemberManagement project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from django.utils.translation import ugettext_lazy as _
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wn_2m*p3v6i&+!cjf-%6j0yc1a3g2j%h@h865@=wcons^4skox'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ENABLE_DEVEL_WARNING = True

ALLOWED_HOSTS = []

# Kosovo is missing from the list of countries
COUNTRIES_OVERRIDE = {
    'XK': _('Kosovo'),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'registry',
    'cookielaw',
    'alumni',
    'custom_auth',
    'atlas',
    'payments',
    'impersonate',
    'django_forms_uikit',
    'django_countries',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'impersonate.middleware.ImpersonateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'MemberManagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'MemberManagement', 'templates')), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'MemberManagement.context_processors.google_analytics_id',
                'registry.context_processors.devel_warning',
                'payments.context_processors.stripe',
                'atlas.context_processors.atlas_allowed',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MemberManagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY")

LOGIN_URL = '/auth/login'
LOGOUT_URL = '/auth/logout'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

GOOGLE_ANALYTICS_ID = None

GSUITE_DOMAIN_NAME = 'jacobs-alumni.de'
GSUITE_OAUTH_CLIENT_ID = '118982546822-515a0fn0ldm96ebev0af5naj6qn8pt9i.apps.googleusercontent.com'

GSUITE_AUTH_FILE = os.environ.get("GSUITE_AUTH_FILE")
GSUITE_ADMIN_USER = 'admin@jacobs-alumni.de'
GSUITE_ORG_PATH = '/Approved Alumni'
GSUITE_PASS_LENGTH = 20

GSUITE_EMAIL_WELCOME_SUBJECT = 'Welcome to the Jacobs Alumni Association!'
GSUITE_EMAIL_WELCOMEBACK_SUBJECT = 'Welcome again to the Jacobs Alumni Association!'
GSUITE_EMAIL_ALL = ['membership@jacobs-alumni.de']

AUTHENTICATION_BACKENDS = [
    'sesame.backends.ModelBackend',
    'django.contrib.auth.backends.ModelBackend',
    'custom_auth.backend.GoogleTokenBackend'
]

SESAME_MAX_AGE = 300  # Emailed tokens expire after 5 minutes

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Import Local settings if available
try:
    from .local_settings import *
except ImportError:
    pass


# Email settings
# https://docs.djangoproject.com/en/1.11/topics/email/

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = ''
EMAIL_USE_TLS = True
EMAIL_PORT = 587

EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_FROM = 'Alumni Association Portal Login <email_login@jacobs-alumni.de>'
